augment: true
batch_size: 128
delta: affine
epochs: 200
exp_name: exp20241025182054
lr: 0.1
optimizer: sgd
save: true
scheduler: step
test_mode: false
transform_scale: 0.1
use_crop: false
use_six: false
